from __future__ import annotations

# Generated by scripts/generate_youtube_string_blob.py
BLOB_FILENAME = "youtube_string.bin"
_INDEX_XOR_MASK = 555741362
_INDEX_XOR_VALUE = 555743792
_PAYLOAD_XOR_MASK = 52785
_PAYLOAD_XOR_VALUE = 52741


def youtube_string_slice() -> tuple[int, int]:
    start = _INDEX_XOR_VALUE ^ _INDEX_XOR_MASK
    payload_size = _PAYLOAD_XOR_VALUE ^ _PAYLOAD_XOR_MASK
    return start, payload_size
