from __future__ import annotations

# Generated by scripts/generate_youtube_string_blob.py
BLOB_FILENAME = "youtube_string.bin"
_INDEX_XOR_MASK = 1352428530
_INDEX_XOR_VALUE = 1352428146
_PAYLOAD_XOR_MASK = 41686
_PAYLOAD_XOR_VALUE = 41698


def youtube_string_slice() -> tuple[int, int]:
    start = _INDEX_XOR_VALUE ^ _INDEX_XOR_MASK
    payload_size = _PAYLOAD_XOR_VALUE ^ _PAYLOAD_XOR_MASK
    return start, payload_size
