#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import codecs
import secrets
from pathlib import Path

# Lightweight obfuscation only: this is intended to reduce simplistic
# auto-detection/scanning noise, not to provide strong secrecy.
# We explicitly accept that the string can still be extracted.


def _encode_youtube_string(youtube_string: str) -> bytes:
    base64_text = base64.b64encode(youtube_string.encode("utf-8")).decode("ascii")
    return codecs.encode(base64_text, "rot_13").encode("ascii")


def _choose_insertion_index(blob_size: int, payload_size: int) -> int:
    if payload_size > blob_size:
        raise ValueError(
            f"Payload ({payload_size} bytes) is larger than blob size ({blob_size} bytes)."
        )
    max_start = blob_size - payload_size
    return secrets.randbelow(max_start + 1)


def _write_metadata_module(
    *,
    metadata_path: Path,
    blob_filename: str,
    index: int,
    payload_size: int,
) -> None:
    index_mask = secrets.randbelow(1 << 31) + 1
    payload_mask = secrets.randbelow(1 << 16) + 1
    module_text = "\n".join(
        [
            "from __future__ import annotations",
            "",
            "# Generated by scripts/generate_youtube_string_blob.py",
            f'BLOB_FILENAME = "{blob_filename}"',
            f"_INDEX_XOR_MASK = {index_mask}",
            f"_INDEX_XOR_VALUE = {index ^ index_mask}",
            f"_PAYLOAD_XOR_MASK = {payload_mask}",
            f"_PAYLOAD_XOR_VALUE = {payload_size ^ payload_mask}",
            "",
            "",
            "def youtube_string_slice() -> tuple[int, int]:",
            "    start = _INDEX_XOR_VALUE ^ _INDEX_XOR_MASK",
            "    payload_size = _PAYLOAD_XOR_VALUE ^ _PAYLOAD_XOR_MASK",
            "    return start, payload_size",
            "",
        ]
    )
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.write_text(module_text, encoding="utf-8")


def build_obfuscated_assets(
    *,
    youtube_string: str,
    blob_path: Path,
    metadata_path: Path,
    blob_size: int,
) -> tuple[int, int]:
    payload = _encode_youtube_string(youtube_string)
    insertion_index = _choose_insertion_index(blob_size, len(payload))
    blob = bytearray(secrets.token_bytes(blob_size))
    blob[insertion_index : insertion_index + len(payload)] = payload

    blob_path.parent.mkdir(parents=True, exist_ok=True)
    blob_path.write_bytes(blob)
    _write_metadata_module(
        metadata_path=metadata_path,
        blob_filename=blob_path.name,
        index=insertion_index,
        payload_size=len(payload),
    )

    return insertion_index, len(payload)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate obfuscated YouTube string assets (binary blob + metadata module)."
    )
    parser.add_argument(
        "--youtube-string",
        "--api-key",
        dest="youtube_string",
        required=True,
        help="The plain YouTube Data string.",
    )
    parser.add_argument(
        "--blob-path",
        default="src/ythist/assets/youtube_string.bin",
        help="Output path for the random binary blob.",
    )
    parser.add_argument(
        "--metadata-path",
        default="src/ythist/youtube_string_blob.py",
        help="Output path for the generated metadata module.",
    )
    parser.add_argument(
        "--blob-size",
        type=int,
        default=4096,
        help="Blob size in bytes. Must be >= encoded payload size.",
    )
    args = parser.parse_args()

    index, payload_size = build_obfuscated_assets(
        youtube_string=args.youtube_string,
        blob_path=Path(args.blob_path),
        metadata_path=Path(args.metadata_path),
        blob_size=args.blob_size,
    )
    print(f"Generated blob at {args.blob_path}")
    print(f"Generated metadata at {args.metadata_path}")
    print(f"YouTube string insertion index: {index}")
    print(f"Encoded payload size: {payload_size}")


if __name__ == "__main__":
    main()
